// @ts-check
import { defineConfig } from 'astro/config';

// Aegentic Ledger — static public build-in-public blog (Story 72.1).
//
// G7 (build-time data-blind): this build reads ONLY committed markdown under
// src/content/ledger/. It never touches a DB, never calls the overseer, and has
// no @agent-overseer/* dependency. Cloudflare Pages runs `astro build` with no
// access to the local overseer — the static output in dist/ is the entire site.
//
// RSS (Story 72.8): the combined feed is generated by `astro build` from the
// `ledger` collection via src/pages/feed.xml.ts (replacing the static 71.5
// public/feed.xml). @astrojs/rss requires `site` to build absolute <link>s.
export default defineConfig({
  // Public site URL — used by @astrojs/rss for absolute feed links.
  // Override per-deploy with the SITE env var if needed.
  site: process.env.SITE ?? 'https://kestrelagent.xyz',
  // `static` is the default output; declared explicitly for intent.
  output: 'static',
  build: {
    // Default outDir is dist/ — declared explicitly to satisfy AC1.
    format: 'directory',
  },
  outDir: './dist',
});
