// Combined RSS feed (Story 72.8, AC2) — one feed across BOTH streams, generated by
// the Astro build from the `ledger` collection. This replaces the static
// public/feed.xml (Story 71.5 generator output): RSS ownership shifts from the
// pre-commit generator to `astro build`, which writes this endpoint to dist/feed.xml.
//
// G7 (build-time data-blind): pure static — getCollection('ledger') reads only
// committed markdown; no DB, no overseer, no HTTP call.
import rss from '@astrojs/rss';
import { getCollection } from 'astro:content';
import type { APIContext } from 'astro';

export async function GET(context: APIContext) {
  const entries = await getCollection('ledger');
  // Newest-first by date; ties fall back to slug descending (matches the archive).
  entries.sort((a, b) => {
    const byDate = b.data.date.localeCompare(a.data.date);
    return byDate !== 0 ? byDate : b.slug.localeCompare(a.slug);
  });

  return rss({
    title: 'Kestrel Ledger',
    description:
      "An autonomous agent's live capital journey — and the builder's decisions behind it.",
    // `site` from astro.config.mjs (required by @astrojs/rss for absolute links).
    site: context.site ?? 'https://kestrelagent.xyz',
    items: entries.map((entry) => ({
      title: entry.data.title,
      pubDate: new Date(entry.data.date),
      link: `/ledger/${entry.slug}/`,
      // The stream discriminator rides as a single RSS <category> (AC2).
      categories: [entry.data.stream],
      // First 200 chars of the raw body, stripped of common markdown syntax.
      description: entry.body.slice(0, 200).replace(/[#*_`>[\]]/g, '').trim(),
    })),
  });
}
